# Generated by Django 6.0.2 on 2026-03-31 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='car',
        ),
    ]
